# Generated by Django 3.2.4 on 2021-06-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='slug', max_length=130),
        ),
    ]
